# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoltApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BoltApp
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  # Add these to your Podfile
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  
  target 'BoltApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testin

    pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  end

  target 'BoltAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

